function [ind ind1] = test_sub2ind(I,Nx,Ny,Nz)

%%  case 2D  
 if nargin == 3
%     PTS = [ 0   0; ...
%             1   0; ...
%            -1   0; ...
%             0   1; ...
%             0  -1];
%         
    PTS = [ 0   0; ...
           -2   0; ...
           -1   0; ...
            1   0; ...
            2   0; ...
            0  -2; ...
            0  -1; ...
            0   1; ...
            0   2];
    [j,i] = ind2sub([Ny,Nx], I);
    ii = i + PTS(:,1);
    jj = j + PTS(:,2);
    ind = sub2ind([Ny, Nx], jj, ii);
    
    %stencil = [0  Ny -Ny 1 -1];
    stencil = [0 -2*Ny -Ny Ny 2*Ny -2 -1 1 2];
    ind1 = I + stencil;
elseif nargin == 4
%% case 3D
%     PTS = [ 0   0   0; ...
%             1   0   0; ...
%            -1   0   0; ...
%             0   1   0; ...
%             0  -1   0; ...
%             0   0   1; ...
%             0   0  -1];
    PTS = [  0   0   0; ...
            -2   0   0; ...
            -1   0   0; ...
             1   0   0; ...
             2   0   0; ...
             0  -2   0; ...
             0  -1   0; ...
             0   1   0; ...
             0   2   0; ...
             0   0  -2; ...
             0   0  -1; ...
             0   0   1; ...
             0   0   2];
    [j,i,k] = ind2sub([Ny,Nx,Nz], I);
    ii = i + PTS(:,1);
    jj = j + PTS(:,2);
    kk = k + PTS(:,3);
    ind = sub2ind([Ny,Nx,Nz],jj,ii,kk);
    
    % stencil = [0 Ny -Ny 1 -1 Nx*Ny -Nx*Ny];
    stencil = [0, -2*Ny,    -Ny,    Ny,    2*Ny, ...
                  -2,       -1,     1,     2,    ...
                  -2*Nx*Ny, -Nx*Ny, Nx*Ny, 2*Nx*Ny];
    ind1 = I + stencil;
end